"""02_author

Revision ID: 05b069ac1c77
Revises: bb75f7e0ba3f
Create Date: 2023-06-16 23:06:27.272405

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '05b069ac1c77'
down_revision = 'bb75f7e0ba3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('author', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'author')
    # ### end Alembic commands ###
